service: tesseract-ocr-layer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: ap-northeast-1
  deploymentBucket: tesseract-ocr-layer

layers:
  tesseract:
    path: layer
    compatibleRuntimes:
      - python3.6
      - python3.7